### ISSUE TITLE
Data Sets

### ISSUE THREAD

**Issue by erinkreiling** [STAT-ATA-ASU/DiscussionSTT2810#7] opened 2015-02-12 15:21 UTC
In case anyone is having issues finding the codebooks, here is the link:
http://www1.appstate.edu/~arnholta/classes/PDS/

**Comment by alanarnholt** [comment] 2015-02-12 18:10
This is a duplicate of https://github.com/STT2810-SP15/DiscussionSTT2810/issues/1

**Comment by alanarnholt** [comment] 2015-02-12 18:11
Please remember to look in closed issues as well....this was the very first issue of the class https://github.com/STT2810-SP15/DiscussionSTT2810/issues/1

**Comment by erinkreiling** [comment] 2015-02-12 18:11
Some students were still confused, so I wanted to repost it.

**Comment by alanarnholt** [comment] 2015-02-12 18:17
I understand....this may be a good opportunity to show everyone how to look in the closed issues as well :) .... as many interesting issues will end of being closed just like this issue.

**Closed** 2015-08-16 10:29 UTC
